[IV-24-25] Objetivo 2
eigenric/bibliofetch pull request #13
Opened 2024-11-20 11:03 UTC by Mario25402

## Sobre la estructura del repositorio

* [x] ¿He seguido las mejores prácticas en el nombre de las clases y ficheros y
   disposición de los mismos?
* [x] ¿He mirado tanto reglas generales (para cualquier repo) como reglas
específicas para el lenguaje con el que se está trabajando?

## Sobre el planteamiento

* [x] ¿Se han planteado una serie de issues, asignados a las historias de
usuario pertinentes, que clarifiquen qué es lo que necesitan los usuarios e
identifiquen las diferentes partes del problema?
* [x] ¿Los issues representan un problema, y no una tarea?

## Sobre el análisis del problema

* [x] ¿Se ha documentado qué análisis se ha hecho sobre el dominio para decir lo
   que se ha creado?
* [x] ¿Se ha documentado por qué se ha elegido que lo creado sea un objeto valor,
   una entidad o un agregado?
* [x] ¿He propuesto un producto mínimamente viable, que en muchos casos será un solo
   objeto valor que no dependa de ningún otro (y que sea la base de muchos
   otros)?.

## Sobre el código

* [x] ¿Todos los mensajes de commit explican el cambio, y no se
      limitan a repetir el nombre del fichero que se ha cambiado?
* [x] ¿Los mensajes de commit siguen el formato estándar y buenas prácticas?
* [x] ¿Se ha hecho una revisión real del código para comprobar que todos
   los atributos y funciones creadas están respaldadas por una HU?
* [x] ¿Todos los issues creados están relacionados con a una HU?
* [x] ¿Ha asignado el propietario/la propietaria del repositorio todos los
issues planteados al *milestone* correspondiente?
* [x] ¿Todos los cambios en el código están asignados a un issue al que se
      referencia en un commit?
* [x] ¿Se ha asignado al mismo milestone el PR que se ha hecho?
* [x] ¿Es el milestone sobre el que estoy trabajando un producto
   mínimamente viable? ¿O tengo que solicitar al product manager que precise de
   qué producto se trata?
* [x] ¿Se ha comprobado que el código entregado sea sintácticamente
correcto?

2024-11-21 12:28 UTC, eigenric commented
Recuerdo que tuvimos un problema en el que se cerró el PR anterior donde yo comenté problemas de visibilidad de exportación que acabo de ver que se han solucionado.  Igualmente se han simplificado los datos clave de libro tal y como hablamos con el profesor.

Faltaría crear una carpeta model con todos los ficheros pertenecientes al mismo paquete para facilitar la importación en futuro.

```
├── src
  │    └── model
  │         ├── datosLibro.go
  │         ├── guiadocente.go
  │         └── libro.go
  └── go.mod
```

2024-11-21 17:49 UTC, eigenric commented
Considero que se ha entregado el código correcto que define las estructuras a modelar que se pedía en el M0, siguiendo el proceso de división de la H01 en Issues cerrados mediante mensajes de commits atómicos.

* [x] ¿Los issues que ha planteado la persona son efectivamente problemas y
evidencian comprensión de las historias de usuario? Si no es así, es mejor que
se le transmita antes de que empiece a crear cualquier código erróneo.
* [x] ¿Has comprobado que efectivamente el compañero/a ha seguido su lista de
comprobación?
* [x] ¿El código creado es una modelización válida de las historias de usuario
creadas por ti, y te sirve como base para programar la lógica de negocio?
* [x] ¿El código creado sigue las mejores prácticas para el lenguaje de
programación que hayáis consensuado, tanto en identificadores, como
nombres de ficheros, como disposición de los diferentes ficheros en el
repositorio? Por ejemplo, ¿todos los commits se refieren a un issue y
aportan código para resolver el problema planteado en el mismo?
* [x] ¿He comprobado que el código compile, o que quien lo ha programado ha lo
ha hecho y documentado en el repositorio?
* [x] ¿He añadido el PR y todos los issues que se resuelvan en él al milestone
correspondiente, que será el primero?
* [x] ¿Cubre totalmente el milestone 0, o hará falta modelización adicional en
el objetivo 4 para poder programar la lógica de negocio?
* [x] En resumen, ¿considero que con lo hecho puedo ponerme a trabajar
directamente en el siguiente milestone, que incluye la lógica de negocio?

2024-11-21 17:52 UTC, Mario25402 commented
@JJ

2024-11-21 18:54 UTC, JJ commented
@eigenric debes aprobar explícitamente.

2024-11-21 19:24 UTC, eigenric approved these changes

2024-11-22 12:04 UTC, JJ requested changes
Mira también los comentarios, por favor.

2024-11-22 12:04 UTC, JJ commented on src/model/libro.go
> +func EsPositivo (num int) bool{
Debes seguir las mejores prácticas en los nombres de los argumentos también. `num` no es un nombre suficientemente explicativo.

2024-11-22 12:04 UTC, JJ commented on src/model/libro.go
> +func setDefaults (obj interface{}) {
Esto es funcionalidad o lógica de negocio, no es parte del modelo.

2024-11-22 12:04 UTC, JJ commented on src/model/guiadocente.go
> +func NuevaGuiaDocente(anio int, asignatura string, basica []Libro, complementaria []Libro) (*GuiaDocente, error){
Los objetos no siempre se crean directamente con los valores de las variables. Para eso no hace falta un objeto. Las clases no solo agrupan, sino que tienen lógica de negocio para crearse a si mismas.
En la HU dice qeu la guía docente está en una página web, es decir, un fichero en este caso. ¿No sería razonable que ese fuera el argumento?

2024-11-22 12:31 UTC, Mario25402 commented on src/model/libro.go
> +func EsPositivo (num int) bool{
Corregido en https://github.com/eigenric/bibliofetch/commit/057912415396b200c1b813aa1ee06db267b34360.

2024-11-22 12:36 UTC, Mario25402 commented on src/model/libro.go
> +func setDefaults (obj interface{}) {
Se ha eliminado ya que se considera una funcionalidad y no se engloba en el M0. https://github.com/eigenric/bibliofetch/commit/c4eb6b6c15d2a92e40a2eea39d5e64fb2264aded

2024-11-22 12:58 UTC, Mario25402 commented on src/model/guiadocente.go
> +func NuevaGuiaDocente(anio int, asignatura string, basica []Libro, complementaria []Libro) (*GuiaDocente, error){
Se cambia para que sea a partir del descriptor del fichero, desde el cuál se creará el objeto. https://github.com/eigenric/bibliofetch/pull/13/commits/47cdb971ec48130cfe714b35ed142b3359380d7a

2024-11-22 13:03 UTC, Mario25402 commented
Sugerencias corregidas @JJ

2024-11-22 14:51 UTC, eigenric approved these changes

2024-11-22 16:15 UTC, JJ approved these changes
:+1:

2024-11-22 16:17 UTC, merged