[IV-24-25] Objetivo 1. Historias de usuario y planificación.
eigenric/bibliofetch pull request #5
Opened 2024-10-07 18:05 UTC by eigenric

* [x] ¿Las historias de usuario y los milestones constituyen una guía suficiente para poder comenzar el desarrollo de un proyecto?
* [x] ¿Los milestones están ordenados correctamente, de forma que el 1 o 0 sea lo primero que hay que empezar a publicar?
* [x] ¿Todos los milestones se construyen sobre el anterior, teniendo un orden lógico el desarrollo?
* [x] ¿El milestone 0 tiene asignada alguna historia de usuario?
* [x] ¿El milestone 0 corresponde con lo mencionado varias veces en clase, y en concreto con lo que se solicita en el objetivo siguiente?
* [x] ¿Todos los milestones describen correctamente un producto y qué lo hace válido, y no un concepto vago, una funcionalidad o una tarea?
* [x] ¿Los milestones son graduales, o hay un salto grande entre ellos?
* [x] ¿Los milestones iniciales son internos, y hay a continuación milestones o productos externos?
* [x] ¿Los milestones son mínimos, es decir, incluyen un producto mínimamente viable para poder avanzar?
* [x] ¿El milestone 0 es mínimo *y* viable?
* [x] ¿Se indica claramente cómo comprobar la viabilidad del PMV de cada hito? Es decir, ¿se dice qué requisitos técnicos tiene que cumplir el producto de cada hito?
* [x] ¿Entre dos milestones consecutivos, no hay ningún PMV posible o por el contrario podrían desarrollarse muchas posibles etapas internas o externas de un proyecto?
* [x] ¿He tenido en cuenta en las historias de usuario que se trata de un proyecto que se desplegará en la nube?
* [x] ¿Están descritos todos los conceptos mencionados en las HUs con suficiente claridad, generalmente en documentos aparte?
* [x] ¿Tienen coherencia suficiente las historias de usuario, y en caso de que no lo tengan, se ha escrito un *user journey* para aclararlo?
* [x] ¿Todas las historias de usuario representan un beneficio para el mismo y se relacionan con la lógica de negocio? Es decir, ¿los usuarios *desean* hacerlo o tú deseas que el usuario te lo pida para hacerlo?

2024-10-08 11:29 UTC, mmnuria reviewed
Además de todas las cuestiones que dejo a continuación, apunto que los milestones no tienen asociadas que HUs se pretenden resolver. Se debería de añadir.

2024-10-08 11:29 UTC, mmnuria commented on docs/user-journeys.md
> +Carlos es un estudiante de 4to año de Filosofía. Usualmente, se encuentra revisando una extensa lista de libros recomendados, no sabiendo por qué libro fundamental empezar.
Esta parte no crees que puede resultar confuso? es algo subjetivo. ¿Que significa "no sabiendo por qué libro fundamental empezar"? ¿Tu aplicación como va a saber de la lista de libros recomendados cual es el "fundamental para empezar"?

2024-10-08 11:29 UTC, mmnuria commented on docs/user-journeys.md
> +Martina es una estudiante Erasmus de 2do año de Química. Le resulta difícil acceder a la bibliografía en español, ya que no es su lengua materna.
¿Que pasa si no se encuentra la bibliográfica en la lengua que quiere? ¿Como vas a asegurar que todos los tipos de lenguas que existen van a obtener el libro en cuestión en esa lengua, aunque este no exista? ¿Vas a crearlo tu? Esta cuestión la veo bastante confusa y muy tediosa, ademas de que puede dar fallos a algunos usuarios que quieran la bibliografía en lenguas que esos libros no se encuentren traducidas.

2024-10-08 11:29 UTC, mmnuria commented on docs/user-stories.md
> +Como estudiante de 4to año de Filosofía, quiero priorizar la bibliografía esencial en función de las recomendaciones del profesor (o de otros estudiantes), para enfocar mis esfuerzos de estudio en lo
¿Como va a saber la aplicación cuales van a ser las bibliografías fundamentales?

2024-10-08 11:29 UTC, mmnuria commented on docs/milestones.md
> +- **Objetivo**: Reconocer el idioma de la bibliografía y filtrarla según el idioma preferido por el usuario.
No entiendo que quiere decir esto. ¿como se sabe cual es el idioma preferido por el alumno? ¿el idioma de la bibliografía que influencia tiene en esto? Según  he entendido, si soy un estudiante que no entiendo español, aunque la bibliografía  este en español, yo la quiero en inglés , entonces ¿que influye el que se reconozca el idioma de la bibliografía ?

2024-10-08 11:29 UTC, mmnuria commented on docs/milestones.md
> +- **Objetivo**: Simplificar la búsqueda de bibliografía permitiendo a los usuarios obtener la bibliografía según su grado, curso e idioma. (Requiere superar el Milestone M1 y M2 )
Esto es algo totalmente diferente a los milestones anteriores, ¿no debería de haber un paso intermedio para que se consiga? ¿no crees que contiene demasiados objetivos? por otro lado, no entiendo el porque se ha introducido esta búsquedas de las guías docentes, si de antemano el usuario las tendrá para obtener la bibliografía de ellas. Siento que se ha desviado del problema principal.

2024-10-08 13:52 UTC, juanbarearojo commented
Buenas he sido asignado para revisar tu pr. Coincido con @mmnuria en varios aspectos además me gustaría puntualizar un par de aspectos.

2024-10-08 14:13 UTC, juanbarearojo commented on docs/milestones.md
> +## [M0] Modelado del Problema
Referente al milestone 0 se menciona en los errores frecuentes del objetivo_1 lo siguiente
"Escribir en el primer milestone (milestone 0) "Modelo del problema" no es suficiente. Primero, tiene que describirse qué producto se va a entregar. Segundo, es importante especificar qué se consideraría un modelo válido del problema. Dado que este producto lo va a recibir realmente el estudiante de manos de otro estudiante en el objetivo 2, es esencial que este formule cuidadosamente, para que esa persona lo entienda, qué es lo que espera recibir."

Ten en cuenta que recibirás un código base a partir del cual trabajaras y si no estableces un estándar de lo que necesitas para milestones futuros es posible que llegues a los siguientes objetivos y te sea complicado seguir trabajando en el proyecto. Piensa que requisitos mínimos tiene que tener le código que te será entregado. Le hará la vida más  fácil a tu compañero y a ti mismo en un futuro.
**Es fundamental que siempre incluyas criterios, ya sean completamente objetivos o, al menos, que permitan justificar por qué se considera un objetivo alcanzable o no**

2024-10-08 14:13 UTC, juanbarearojo commented on docs/milestones.md
> +- **Entregable**: Módulo que, dado un conjunto de libros, identifica el idioma de cada libro y filtra los libros según el idioma preferido por el usuario.
También quiero establecer que el reconocimiento del idioma en un texto es un tarea complicada. Es probable que tengas que depender de herramientas externas para poder llegar a cabo este tarea. Implementar un reconocedor de idioma no es tarea sencilla. Creo que este milestone aun siendo una tarea que podría llegar a ser interesante, se escapa del scope de la asignatura al depende en gran medida de otra herramientas.

2024-10-08 15:46 UTC, eigenric commented on docs/user-journeys.md
> +Carlos es un estudiante de 4to año de Filosofía. Usualmente, se encuentra revisando una extensa lista de libros recomendados, no sabiendo por qué libro fundamental empezar.
Aunque la necesidad del usuario es esta, la manera en que la aplicación podría ayudar podría ser permitiendo marcar como Favorito aquellos libros que el profesor haya indicado (en clase) como más relevantes. Quizás debería modificar esta interacción en el user-journey e historia de usuario.

2024-10-08 15:56 UTC, eigenric commented on docs/user-journeys.md
> +Martina es una estudiante Erasmus de 2do año de Química. Le resulta difícil acceder a la bibliografía en español, ya que no es su lengua materna.
Esta historia de usuario plantea la necesidad de un estudiante de erasmus.  Se basa en el predominio de bibliografía mezclada en inglés y español. Tendría sentido que la herramienta ordenase ofreciendo primero la de inglés para este usuario. Si no existe, buscar traducciones queda fuera del ámbito del hito.

2024-10-08 16:00 UTC, eigenric commented on docs/user-stories.md
> +Como estudiante de 4to año de Filosofía, quiero priorizar la bibliografía esencial en función de las recomendaciones del profesor (o de otros estudiantes), para enfocar mis esfuerzos de estudio en lo
La bibliografía fundamental y complementaria queda bien determinada por la guía docente en dos listas. Sin embargo, incluso la fundamental puede ser extensa debiendo priorizar. De ahí la interacción de Favorito que antes comentaba como solución posible.

2024-10-08 16:02 UTC, eigenric commented on docs/milestones.md
> +- **Objetivo**: Reconocer el idioma de la bibliografía y filtrarla según el idioma preferido por el usuario.
El usuario debería elegir si prefiere priorizar libros en inglés o es español.  La herramienta debería ser capaz de reconocer el idioma (no trivial) y ordenarlos según esta preferencia.

2024-10-08 16:13 UTC, eigenric commented on docs/milestones.md
> +- **Objetivo**: Simplificar la búsqueda de bibliografía permitiendo a los usuarios obtener la bibliografía según su grado, curso e idioma. (Requiere superar el Milestone M1 y M2 )
En principio, el estudiante quiere acceder a la bibliografía de sus asignaturas. Por lo que podría facilitarle dar como entrada en su lugar sólo los título de sus asignaturas. Entonces el hito intermedio sería dado un titulo de la asignatura, obtener su guía docente.

2024-10-08 16:16 UTC, juanbarearojo commented on docs/milestones.md
> +# Milestones - Bibliofetch
Debes añadir en cada milestone que historias de usuario tiene asociadas

2024-10-08 18:24 UTC, mmnuria commented on docs/milestones.md
> +- **Objetivo**: Simplificar la búsqueda de bibliografía permitiendo a los usuarios obtener la bibliografía según su grado, curso e idioma. (Requiere superar el Milestone M1 y M2 )
En ese caso, no crees que puede ser interesante que el milestone 1 realice esa tarea? de manera que, el orden a seguir en la aplicación sea:

1. Títulos de sus asignaturas.
2. Obtención de las guías docentes.
3. Obtención bibliografías.
.
.
.

El orden mas o menos a seguir para conseguir una lógica de negocio correcta, creo que puede ser este, no se que puedes opinar. De esta manera puedes reestructurar los milestones y ordenarlos, ademas de simplificar algunos de ellos. Recuerda, cuantas mas tareas sencillas puedas dividir el problema, mas fácil será llevarlo a cabo!

2024-10-08 18:25 UTC, mmnuria commented on docs/milestones.md
> +- **Objetivo**: Reconocer el idioma de la bibliografía y filtrarla según el idioma preferido por el usuario.
de acuerdo entonces sería conveniente perfilar el "idioma preferido por el usuario" por algo como "seleccionar su idioma de preferencia entre el ingles y español".

2024-10-08 18:26 UTC, mmnuria commented on docs/user-stories.md
> +Como estudiante de 4to año de Filosofía, quiero priorizar la bibliografía esencial en función de las recomendaciones del profesor (o de otros estudiantes), para enfocar mis esfuerzos de estudio en lo
de acuerdo, entonces estaría bien si puedes matizar esa parte que me has explicado para que quede bien clara, ya que, para mi ha sido algo confuso.

2024-10-08 18:27 UTC, mmnuria commented on docs/user-journeys.md
> +Martina es una estudiante Erasmus de 2do año de Química. Le resulta difícil acceder a la bibliografía en español, ya que no es su lengua materna.
Por lo tanto, habrá una sección  que recoja diferentes usuarios dependiendo si son de erasmus o no? Eso no aparece en ningún  milestone no?

2024-10-08 18:28 UTC, mmnuria commented on docs/user-journeys.md
> +Carlos es un estudiante de 4to año de Filosofía. Usualmente, se encuentra revisando una extensa lista de libros recomendados, no sabiendo por qué libro fundamental empezar.
Aunque sigo viendo difícil el como vas a señalar como favoritos esos libros desde la aplicación antes de ofrecerle la guía docente.

2024-10-09 09:31 UTC, MatteoImbrosciano commented
¡Hola! Me han asignado el rol de revisor de tu PR. Estoy de acuerdo con @mmnuria en los aspectos que ha señalado, y también coincido con @juanbarearojo en que el reconocimiento lingüístico en un texto es una tarea complicada. Además, sería conveniente agregar las historias de usuario asociadas a cada hito.

2024-10-10 11:44 UTC, eigenric commented on docs/milestones.md
> +## [M0] Modelado del Problema
De acuerdo. Reescribiré este apartado para no cometer este error frecuente.

2024-10-10 12:04 UTC, eigenric commented on docs/milestones.md
> +- **Entregable**: Módulo que, dado un conjunto de libros, identifica el idioma de cada libro y filtra los libros según el idioma preferido por el usuario.
Es cierto. Lo mejor será que abandone este milestone y lo reemplace con otro viable de implementar desde 0, sin dependencia de herramientas externas. 😅

2024-10-10 12:11 UTC, eigenric commented on docs/milestones.md
> +- **Entregable**: Módulo que, dado un conjunto de libros, identifica el idioma de cada libro y filtra los libros según el idioma preferido por el usuario.
Es cierto que la manera más viable era dependiendo de una librería externa. Dado que también le ha parecido confuso a @mmnuria, he pensado en añadir una historia de usuario que tenga un problema más viable para resolver.

2024-10-10 16:35 UTC, eigenric commented on docs/milestones.md
> +- **Objetivo**: Simplificar la búsqueda de bibliografía permitiendo a los usuarios obtener la bibliografía según su grado, curso e idioma. (Requiere superar el Milestone M1 y M2 )
El problema con este orden es que no sería un producto mínimo viable lo que se obtendría en los primeros milestones pues no sería capaz de obtener la bibliografía todavía. Voy a hacer caso a tu recomendación de que a lo mejor son demasiados hitos y voy a considerar planificar solo hasta el milestone [M02] (por ahora).

2024-10-10 17:26 UTC, eigenric commented
Buenas tardes, he resuelto los siguientes problemas que se me han señalado @mmnuria , @juanbarearojo , @MatteoImbrosciano :
- [x] Asignación de HUs a cada Milestone
- [x] [HU2] asignada a [M2] para gestión de favoritos
- [x] Milestone relacionado con los idiomas descontinuado por lógica compleja
- [x] Milestone relacionado con asignaturas, cursos y grados se replanteará si da tiempo.
- [x] Milestone 0 describe un modelo válido y describe qué producto se va a entregar. 
- [x] Nueva HU [HU4] para estudiantes con TFG asociada al nuevo [M4] (Exportar en formato de cita)

2024-10-11 11:32 UTC, eigenric commented
¿Estaría listo para revisión? @juanbarearojo @MatteoImbrosciano @mmnuria

2024-10-12 12:08 UTC, mmnuria reviewed
Soluciona cada uno de los comentarios anteriores, igualmente he dejado una cosita mas a solucionar. Con todo eso por mi parte estaría aceptado.

2024-10-12 12:08 UTC, mmnuria commented on docs/milestones.md
> +**Historias de Usuario**: [HU1], [HU2], [HU3]
asignar tantas HUs a un mismo hito es demasiado, ya que, no sería necesario crear mas milestones, ya que con solo uno estás diciendo que se solucionaría todas las Hus de tu problema.

2024-10-12 12:15 UTC, juanbarearojo commented
Por mi parte veo que has cambiado varios aspectos y lo veo bastante mejor.

2024-10-12 12:15 UTC, juanbarearojo approved these changes

2024-10-17 10:40 UTC, eigenric commented on docs/milestones.md
> +**Historias de Usuario**: [HU1]
Ahora para el Milestone 0 se comenzará con la Historia de Usuario número 1.

2024-10-17 10:45 UTC, eigenric commented
He corregido el último comentario de @mmnuria sobre la asignación de HUs
Espero vuestra confirmación para revisión @juanbarearojo @MatteoImbrosciano.

2024-10-18 12:00 UTC, eigenric commented
Acabo de corregir los comentarios de @juanbarearojo en clase.

* [x] No aportar solución en el milestone 0
* [x] Ampliar historia de usuario de Carlos, estudiante de Filosofía.
* [x] Typo en milestone 3

2024-10-18 12:04 UTC, juanbarearojo approved these changes

2024-10-18 12:11 UTC, eigenric commented
¿Algún comentario @MatteoImbrosciano?

2024-10-18 14:13 UTC, MatteoImbrosciano commented
Viendo los cambios realizados creo que por lo que a mí respecta se ha conseguido el objetivo. Puedes solicitar la revisión del profesor.

2024-10-21 05:50 UTC, JJ commented
> Viendo los cambios realizados creo que por lo que a mí respecta se ha conseguido el objetivo. Puedes solicitar la revisión del profesor.

Por favor, aprueba explícitamente usando el botón de review changes arriba a la derecha.

2024-10-24 10:43 UTC, eigenric commented
@MatteoImbrosciano @mmnuria ¿Podéis aprobar explícitamente los cambios con el botón de review changes?

2024-10-24 11:07 UTC, JJ requested changes
Por favor, revisa cuidadosamente los errores frecuentes y trata de adaptar tu comprensión del concepto de milestone y de historia de usuario y expresarlo aquí, haciendo cambios atómicos que reflejen esta comprensión.

2024-10-24 11:07 UTC, JJ commented on docs/git/git_config.png
Estos cambios debéis hacerlos en main, no en esta rama. La rama debe contener sólo lo necesario para corregir.

2024-10-24 11:07 UTC, JJ commented on docs/milestones.md
> +# Milestones - Bibliofetch
Debes resolver siempre indicando el commit donde se ha resuelto.

2024-10-24 11:07 UTC, JJ commented on docs/milestones.md
> +**Objetivo**: A partir de las Historias de Usuario (HUs), reconocer los elementos clave del dominio y sus relaciones con el fin de modelar un sistema que facilite el acceso y gestión de la bibliograf
Por favor, consulta [los errores frecuentes de este objetivo](https://github.com/JJ/IV-/blob/master/errores/objetivo-1.md). Explícitamente, en las primeras líneas, señala como error al menos dos de las cosas que has indicado aquí.

2024-10-24 16:04 UTC, eigenric commented on docs/git/git_config.png
Para corregir el error he seguido las indicaciones de "añadirlo a la rama principal y quitarlo de la secundaria haciendo un rebase (añadiendo a la principal y mergeando de la principal a la secundaria)."

2024-10-24 16:54 UTC, MatteoImbrosciano approved these changes

2024-10-24 17:25 UTC, eigenric commented
Tras consultar los errores frecuentes del objetivo he revertido aquellas señalizaciones de los revisores que no eran correctas (como asignar historia de usuario a cada milestone), además de mi error fundamental de pretender que guiarme por otras soluciones aceptadas pueda favorecer a mi comprensión del problema y en mi aprendizaje personal.

2024-10-24 17:57 UTC, eigenric commented
@JJ

2024-10-25 10:55 UTC, JJ requested changes
Por favor, dale una vuelta y trata también de quitar los ficheros innecesarios.

2024-10-25 10:55 UTC, JJ commented on docs/milestones.md
> +Partir de las historias de usuario para reconocer los elementos clave del dominio y las relaciones entre ellos.
Esto tiene un nombre. Por favor úsalo. Tampoco uses "especificación" y luego "reconocer"

2024-10-25 10:55 UTC, JJ commented on docs/milestones.md
> +    - Es viable si la formulación del modelo de asignatura permite distinguir libros prioritarios.
Estás haciendo referencia a detalles específicos. Estos detalles tienen que salir del desarrollo.

2024-10-25 10:55 UTC, JJ commented on docs/milestones.md
> +## [M0] Especificación del problema
¿Dónde está especificado el problema?

2024-10-25 10:55 UTC, JJ commented on docs/milestones.md
> +    - Se considera viable cuando otro desarrollador puede comprender el modelo y continuar su desarrollo a partir de la especificación.
El modelo ¿de qué? ¿Donde está especificado de donde hay que extraer el modelo?

2024-10-25 12:10 UTC, eigenric commented
He quitado los archivos innecesarios (realizando un rebase en esta rama y posterior el merge de esta main a la rama).
 
En cuanto a los milestones, he preferido utilizar *Representación del Problema* como forma de referirme al Modelo de problema para el Milestone 0 en lugar de Especificación pues una representación es algo más cercano al concepto que queremos describir con Modelo en el cual se definen las entidades necesarias que lo "representan" según cierto criterio del desarrollador (no detallado) y viabilidad.
Además he adaptado mi comprensión de la relación entre Milestones e Historias de usuario, describiendo qué necesidad del usuario se pretende resolver con cada hito.

@JJ

2024-10-25 12:25 UTC, JJ requested changes
Ánimo que ya queda menos.

2024-10-25 12:25 UTC, JJ commented on docs/milestones.md
> +**Entregables:** Código con las entidades fundamentales relativas a la Gestión Bibliográfica.
Tienes *siempre* que hacer referencia a las historias de usuario, que son los documentos técnicos que guían el desarrollo.

2024-10-25 12:25 UTC, JJ commented on docs/milestones.md
> +    - Se utilizan las buenas prácticas del lenguaje de programación en la organización de archivos y entidades.
¿Y? ¿Tendrá que contener la representación o el modelo, no?

2024-10-25 12:25 UTC, JJ commented on docs/milestones.md
> +En lo relativo a la primera historia de usuario, definir las estructuras que modelan el problema de Extracción de Bibliografía.
no le llames al problema de ninguna forma. La HU describe el problema. Si fuera más simple describirlo, la hU sería más simple.

2024-10-31 11:39 UTC, eigenric commented
He hecho referencia a la HUs, incluyendo además sus enlaces. Ahora la viabilidad del milestone 0 consistirá además en la presencia del código que define las estructuras. Ya no menciono el problema de ninguna forma que no sea una simple HU. 
Por otro lado, he cambiado de orden de prioridad el milestone 3 al 2 pues considero que es un problema más interesante y supone un paso incremental a partir del 1. 

@JJ

2024-10-31 11:52 UTC, JJ reviewed
Recuerda que lo importante aquí es guiar al desarrollador para que analice el problema y lo resuelva en diferentes etapas, no decirle de antemano lo que tiene que extraer o qué va a resultar de ese modelo.

2024-10-31 11:52 UTC, JJ commented on docs/milestones.md
> +## [M2] Bibliofetch exporta la bibliografía en formato BibTeX
Ya hemos hablado varias veces de esto en clase, sobre hacer o no los milestones por encima del 1. No bloquea que se acepte, pero realmente cuando se acepte ¿crees que merece la pena siquiera pegarte el trabajo de pasarlos a GitHub?

2024-10-31 11:52 UTC, JJ commented on docs/milestones.md
> +- **Entregable**: Módulo que recibe una guía docente como entrada web, extrae la información bibliográfica y la organiza en un formato estructurado por atributos (título, autor, editorial, año, ISBN,
Por favor, no pongáis detalles. Los detalles los tiene que extraer el desarrollador de la historia de usuario. Si ya le estáis diciendo qué tiene que hacer, no hace falta que intervenga para nada.

2024-10-31 12:13 UTC, eigenric commented
No dar detalles del problema para permitir que el desarrollador elija una manera viable de resolver la necesidad del usuario.
Por otro lado, he suprimido los milestones a partir del 1 pues los siguientes se corresponderán con hitos relacionados con API y despliegue. Sin embargo, en un futuro podrían reconsiderarse como trabajo futuro o mejoras del proyecto.

@JJ

2024-10-31 12:36 UTC, JJ approved these changes
👍

2024-10-31 12:54 UTC, merged